// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: iks.proto
#ifndef GRPC_iks_2eproto__INCLUDED
#define GRPC_iks_2eproto__INCLUDED

#include "iks.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

// The IKSF service, exposed to remote client.
// This API is used by LibLogicalAccess to provide
// server side cryptography.
class IKSService final {
 public:
  static constexpr char const* service_full_name() {
    return "IKSService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Request random data from the server.
    virtual ::grpc::Status GenRandom(::grpc::ClientContext* context, const ::CMSG_GenRandom& request, ::SMSG_GenRandom* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_GenRandom>> AsyncGenRandom(::grpc::ClientContext* context, const ::CMSG_GenRandom& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_GenRandom>>(AsyncGenRandomRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_GenRandom>> PrepareAsyncGenRandom(::grpc::ClientContext* context, const ::CMSG_GenRandom& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_GenRandom>>(PrepareAsyncGenRandomRaw(context, request, cq));
    }
    // Generic AES Encryption routine.
    // No padding management.
    virtual ::grpc::Status AESEncrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::SMSG_AESResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_AESResult>> AsyncAESEncrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_AESResult>>(AsyncAESEncryptRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_AESResult>> PrepareAsyncAESEncrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_AESResult>>(PrepareAsyncAESEncryptRaw(context, request, cq));
    }
    // Generic AES Decryption routine.
    // No padding management.
    virtual ::grpc::Status AESDecrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::SMSG_AESResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_AESResult>> AsyncAESDecrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_AESResult>>(AsyncAESDecryptRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_AESResult>> PrepareAsyncAESDecrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_AESResult>>(PrepareAsyncAESDecryptRaw(context, request, cq));
    }
    // Desfire ISO Authentication -- Step 1
    virtual ::grpc::Status DESFireISOAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireISOAuth_Step1& request, ::SMSG_DesfireISOAuth_Step1* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireISOAuth_Step1>> AsyncDESFireISOAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireISOAuth_Step1& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireISOAuth_Step1>>(AsyncDESFireISOAuth1Raw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireISOAuth_Step1>> PrepareAsyncDESFireISOAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireISOAuth_Step1& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireISOAuth_Step1>>(PrepareAsyncDESFireISOAuth1Raw(context, request, cq));
    }
    // Desfire ISO Authentication -- Step 2
    virtual ::grpc::Status DESFireISOAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::SMSG_DesfireAuth_Step2* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireAuth_Step2>> AsyncDESFireISOAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireAuth_Step2>>(AsyncDESFireISOAuth2Raw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireAuth_Step2>> PrepareAsyncDESFireISOAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireAuth_Step2>>(PrepareAsyncDESFireISOAuth2Raw(context, request, cq));
    }
    // Desfire AES Authentication -- Step 1
    virtual ::grpc::Status DESFireAESAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireAESAuth_Step1& request, ::SMSG_DesfireAESAuth_Step1* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireAESAuth_Step1>> AsyncDESFireAESAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireAESAuth_Step1& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireAESAuth_Step1>>(AsyncDESFireAESAuth1Raw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireAESAuth_Step1>> PrepareAsyncDESFireAESAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireAESAuth_Step1& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireAESAuth_Step1>>(PrepareAsyncDESFireAESAuth1Raw(context, request, cq));
    }
    // Desfire AES Authentication -- Step 2
    virtual ::grpc::Status DESFireAESAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::SMSG_DesfireAuth_Step2* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireAuth_Step2>> AsyncDESFireAESAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireAuth_Step2>>(AsyncDESFireAESAuth2Raw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireAuth_Step2>> PrepareAsyncDESFireAESAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireAuth_Step2>>(PrepareAsyncDESFireAESAuth2Raw(context, request, cq));
    }
    // Generate DESFire change-key cryptogram where both keys
    // are stored by IKS.
    // This call is forward to IKSD which perform the cryptogram generation.
    virtual ::grpc::Status DESFireChangeKey(::grpc::ClientContext* context, const ::CMSG_DesfireChangeKey& request, ::SMSG_DesfireChangeKey* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireChangeKey>> AsyncDESFireChangeKey(::grpc::ClientContext* context, const ::CMSG_DesfireChangeKey& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireChangeKey>>(AsyncDESFireChangeKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireChangeKey>> PrepareAsyncDESFireChangeKey(::grpc::ClientContext* context, const ::CMSG_DesfireChangeKey& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireChangeKey>>(PrepareAsyncDESFireChangeKeyRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Request random data from the server.
      virtual void GenRandom(::grpc::ClientContext* context, const ::CMSG_GenRandom* request, ::SMSG_GenRandom* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GenRandom(::grpc::ClientContext* context, const ::CMSG_GenRandom* request, ::SMSG_GenRandom* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Generic AES Encryption routine.
      // No padding management.
      virtual void AESEncrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation* request, ::SMSG_AESResult* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AESEncrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation* request, ::SMSG_AESResult* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Generic AES Decryption routine.
      // No padding management.
      virtual void AESDecrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation* request, ::SMSG_AESResult* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AESDecrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation* request, ::SMSG_AESResult* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Desfire ISO Authentication -- Step 1
      virtual void DESFireISOAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireISOAuth_Step1* request, ::SMSG_DesfireISOAuth_Step1* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DESFireISOAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireISOAuth_Step1* request, ::SMSG_DesfireISOAuth_Step1* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Desfire ISO Authentication -- Step 2
      virtual void DESFireISOAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2* request, ::SMSG_DesfireAuth_Step2* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DESFireISOAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2* request, ::SMSG_DesfireAuth_Step2* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Desfire AES Authentication -- Step 1
      virtual void DESFireAESAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireAESAuth_Step1* request, ::SMSG_DesfireAESAuth_Step1* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DESFireAESAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireAESAuth_Step1* request, ::SMSG_DesfireAESAuth_Step1* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Desfire AES Authentication -- Step 2
      virtual void DESFireAESAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2* request, ::SMSG_DesfireAuth_Step2* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DESFireAESAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2* request, ::SMSG_DesfireAuth_Step2* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Generate DESFire change-key cryptogram where both keys
      // are stored by IKS.
      // This call is forward to IKSD which perform the cryptogram generation.
      virtual void DESFireChangeKey(::grpc::ClientContext* context, const ::CMSG_DesfireChangeKey* request, ::SMSG_DesfireChangeKey* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DESFireChangeKey(::grpc::ClientContext* context, const ::CMSG_DesfireChangeKey* request, ::SMSG_DesfireChangeKey* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_GenRandom>* AsyncGenRandomRaw(::grpc::ClientContext* context, const ::CMSG_GenRandom& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_GenRandom>* PrepareAsyncGenRandomRaw(::grpc::ClientContext* context, const ::CMSG_GenRandom& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_AESResult>* AsyncAESEncryptRaw(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_AESResult>* PrepareAsyncAESEncryptRaw(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_AESResult>* AsyncAESDecryptRaw(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_AESResult>* PrepareAsyncAESDecryptRaw(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireISOAuth_Step1>* AsyncDESFireISOAuth1Raw(::grpc::ClientContext* context, const ::CMSG_DesfireISOAuth_Step1& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireISOAuth_Step1>* PrepareAsyncDESFireISOAuth1Raw(::grpc::ClientContext* context, const ::CMSG_DesfireISOAuth_Step1& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireAuth_Step2>* AsyncDESFireISOAuth2Raw(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireAuth_Step2>* PrepareAsyncDESFireISOAuth2Raw(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireAESAuth_Step1>* AsyncDESFireAESAuth1Raw(::grpc::ClientContext* context, const ::CMSG_DesfireAESAuth_Step1& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireAESAuth_Step1>* PrepareAsyncDESFireAESAuth1Raw(::grpc::ClientContext* context, const ::CMSG_DesfireAESAuth_Step1& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireAuth_Step2>* AsyncDESFireAESAuth2Raw(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireAuth_Step2>* PrepareAsyncDESFireAESAuth2Raw(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireChangeKey>* AsyncDESFireChangeKeyRaw(::grpc::ClientContext* context, const ::CMSG_DesfireChangeKey& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SMSG_DesfireChangeKey>* PrepareAsyncDESFireChangeKeyRaw(::grpc::ClientContext* context, const ::CMSG_DesfireChangeKey& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GenRandom(::grpc::ClientContext* context, const ::CMSG_GenRandom& request, ::SMSG_GenRandom* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_GenRandom>> AsyncGenRandom(::grpc::ClientContext* context, const ::CMSG_GenRandom& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_GenRandom>>(AsyncGenRandomRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_GenRandom>> PrepareAsyncGenRandom(::grpc::ClientContext* context, const ::CMSG_GenRandom& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_GenRandom>>(PrepareAsyncGenRandomRaw(context, request, cq));
    }
    ::grpc::Status AESEncrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::SMSG_AESResult* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_AESResult>> AsyncAESEncrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_AESResult>>(AsyncAESEncryptRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_AESResult>> PrepareAsyncAESEncrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_AESResult>>(PrepareAsyncAESEncryptRaw(context, request, cq));
    }
    ::grpc::Status AESDecrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::SMSG_AESResult* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_AESResult>> AsyncAESDecrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_AESResult>>(AsyncAESDecryptRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_AESResult>> PrepareAsyncAESDecrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_AESResult>>(PrepareAsyncAESDecryptRaw(context, request, cq));
    }
    ::grpc::Status DESFireISOAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireISOAuth_Step1& request, ::SMSG_DesfireISOAuth_Step1* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireISOAuth_Step1>> AsyncDESFireISOAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireISOAuth_Step1& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireISOAuth_Step1>>(AsyncDESFireISOAuth1Raw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireISOAuth_Step1>> PrepareAsyncDESFireISOAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireISOAuth_Step1& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireISOAuth_Step1>>(PrepareAsyncDESFireISOAuth1Raw(context, request, cq));
    }
    ::grpc::Status DESFireISOAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::SMSG_DesfireAuth_Step2* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireAuth_Step2>> AsyncDESFireISOAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireAuth_Step2>>(AsyncDESFireISOAuth2Raw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireAuth_Step2>> PrepareAsyncDESFireISOAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireAuth_Step2>>(PrepareAsyncDESFireISOAuth2Raw(context, request, cq));
    }
    ::grpc::Status DESFireAESAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireAESAuth_Step1& request, ::SMSG_DesfireAESAuth_Step1* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireAESAuth_Step1>> AsyncDESFireAESAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireAESAuth_Step1& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireAESAuth_Step1>>(AsyncDESFireAESAuth1Raw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireAESAuth_Step1>> PrepareAsyncDESFireAESAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireAESAuth_Step1& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireAESAuth_Step1>>(PrepareAsyncDESFireAESAuth1Raw(context, request, cq));
    }
    ::grpc::Status DESFireAESAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::SMSG_DesfireAuth_Step2* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireAuth_Step2>> AsyncDESFireAESAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireAuth_Step2>>(AsyncDESFireAESAuth2Raw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireAuth_Step2>> PrepareAsyncDESFireAESAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireAuth_Step2>>(PrepareAsyncDESFireAESAuth2Raw(context, request, cq));
    }
    ::grpc::Status DESFireChangeKey(::grpc::ClientContext* context, const ::CMSG_DesfireChangeKey& request, ::SMSG_DesfireChangeKey* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireChangeKey>> AsyncDESFireChangeKey(::grpc::ClientContext* context, const ::CMSG_DesfireChangeKey& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireChangeKey>>(AsyncDESFireChangeKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireChangeKey>> PrepareAsyncDESFireChangeKey(::grpc::ClientContext* context, const ::CMSG_DesfireChangeKey& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireChangeKey>>(PrepareAsyncDESFireChangeKeyRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GenRandom(::grpc::ClientContext* context, const ::CMSG_GenRandom* request, ::SMSG_GenRandom* response, std::function<void(::grpc::Status)>) override;
      void GenRandom(::grpc::ClientContext* context, const ::CMSG_GenRandom* request, ::SMSG_GenRandom* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AESEncrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation* request, ::SMSG_AESResult* response, std::function<void(::grpc::Status)>) override;
      void AESEncrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation* request, ::SMSG_AESResult* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AESDecrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation* request, ::SMSG_AESResult* response, std::function<void(::grpc::Status)>) override;
      void AESDecrypt(::grpc::ClientContext* context, const ::CMSG_AESOperation* request, ::SMSG_AESResult* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DESFireISOAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireISOAuth_Step1* request, ::SMSG_DesfireISOAuth_Step1* response, std::function<void(::grpc::Status)>) override;
      void DESFireISOAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireISOAuth_Step1* request, ::SMSG_DesfireISOAuth_Step1* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DESFireISOAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2* request, ::SMSG_DesfireAuth_Step2* response, std::function<void(::grpc::Status)>) override;
      void DESFireISOAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2* request, ::SMSG_DesfireAuth_Step2* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DESFireAESAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireAESAuth_Step1* request, ::SMSG_DesfireAESAuth_Step1* response, std::function<void(::grpc::Status)>) override;
      void DESFireAESAuth1(::grpc::ClientContext* context, const ::CMSG_DesfireAESAuth_Step1* request, ::SMSG_DesfireAESAuth_Step1* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DESFireAESAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2* request, ::SMSG_DesfireAuth_Step2* response, std::function<void(::grpc::Status)>) override;
      void DESFireAESAuth2(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2* request, ::SMSG_DesfireAuth_Step2* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DESFireChangeKey(::grpc::ClientContext* context, const ::CMSG_DesfireChangeKey* request, ::SMSG_DesfireChangeKey* response, std::function<void(::grpc::Status)>) override;
      void DESFireChangeKey(::grpc::ClientContext* context, const ::CMSG_DesfireChangeKey* request, ::SMSG_DesfireChangeKey* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::SMSG_GenRandom>* AsyncGenRandomRaw(::grpc::ClientContext* context, const ::CMSG_GenRandom& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SMSG_GenRandom>* PrepareAsyncGenRandomRaw(::grpc::ClientContext* context, const ::CMSG_GenRandom& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SMSG_AESResult>* AsyncAESEncryptRaw(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SMSG_AESResult>* PrepareAsyncAESEncryptRaw(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SMSG_AESResult>* AsyncAESDecryptRaw(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SMSG_AESResult>* PrepareAsyncAESDecryptRaw(::grpc::ClientContext* context, const ::CMSG_AESOperation& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireISOAuth_Step1>* AsyncDESFireISOAuth1Raw(::grpc::ClientContext* context, const ::CMSG_DesfireISOAuth_Step1& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireISOAuth_Step1>* PrepareAsyncDESFireISOAuth1Raw(::grpc::ClientContext* context, const ::CMSG_DesfireISOAuth_Step1& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireAuth_Step2>* AsyncDESFireISOAuth2Raw(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireAuth_Step2>* PrepareAsyncDESFireISOAuth2Raw(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireAESAuth_Step1>* AsyncDESFireAESAuth1Raw(::grpc::ClientContext* context, const ::CMSG_DesfireAESAuth_Step1& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireAESAuth_Step1>* PrepareAsyncDESFireAESAuth1Raw(::grpc::ClientContext* context, const ::CMSG_DesfireAESAuth_Step1& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireAuth_Step2>* AsyncDESFireAESAuth2Raw(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireAuth_Step2>* PrepareAsyncDESFireAESAuth2Raw(::grpc::ClientContext* context, const ::CMSG_DesfireAuth_Step2& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireChangeKey>* AsyncDESFireChangeKeyRaw(::grpc::ClientContext* context, const ::CMSG_DesfireChangeKey& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SMSG_DesfireChangeKey>* PrepareAsyncDESFireChangeKeyRaw(::grpc::ClientContext* context, const ::CMSG_DesfireChangeKey& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GenRandom_;
    const ::grpc::internal::RpcMethod rpcmethod_AESEncrypt_;
    const ::grpc::internal::RpcMethod rpcmethod_AESDecrypt_;
    const ::grpc::internal::RpcMethod rpcmethod_DESFireISOAuth1_;
    const ::grpc::internal::RpcMethod rpcmethod_DESFireISOAuth2_;
    const ::grpc::internal::RpcMethod rpcmethod_DESFireAESAuth1_;
    const ::grpc::internal::RpcMethod rpcmethod_DESFireAESAuth2_;
    const ::grpc::internal::RpcMethod rpcmethod_DESFireChangeKey_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Request random data from the server.
    virtual ::grpc::Status GenRandom(::grpc::ServerContext* context, const ::CMSG_GenRandom* request, ::SMSG_GenRandom* response);
    // Generic AES Encryption routine.
    // No padding management.
    virtual ::grpc::Status AESEncrypt(::grpc::ServerContext* context, const ::CMSG_AESOperation* request, ::SMSG_AESResult* response);
    // Generic AES Decryption routine.
    // No padding management.
    virtual ::grpc::Status AESDecrypt(::grpc::ServerContext* context, const ::CMSG_AESOperation* request, ::SMSG_AESResult* response);
    // Desfire ISO Authentication -- Step 1
    virtual ::grpc::Status DESFireISOAuth1(::grpc::ServerContext* context, const ::CMSG_DesfireISOAuth_Step1* request, ::SMSG_DesfireISOAuth_Step1* response);
    // Desfire ISO Authentication -- Step 2
    virtual ::grpc::Status DESFireISOAuth2(::grpc::ServerContext* context, const ::CMSG_DesfireAuth_Step2* request, ::SMSG_DesfireAuth_Step2* response);
    // Desfire AES Authentication -- Step 1
    virtual ::grpc::Status DESFireAESAuth1(::grpc::ServerContext* context, const ::CMSG_DesfireAESAuth_Step1* request, ::SMSG_DesfireAESAuth_Step1* response);
    // Desfire AES Authentication -- Step 2
    virtual ::grpc::Status DESFireAESAuth2(::grpc::ServerContext* context, const ::CMSG_DesfireAuth_Step2* request, ::SMSG_DesfireAuth_Step2* response);
    // Generate DESFire change-key cryptogram where both keys
    // are stored by IKS.
    // This call is forward to IKSD which perform the cryptogram generation.
    virtual ::grpc::Status DESFireChangeKey(::grpc::ServerContext* context, const ::CMSG_DesfireChangeKey* request, ::SMSG_DesfireChangeKey* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GenRandom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GenRandom() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GenRandom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenRandom(::grpc::ServerContext* /*context*/, const ::CMSG_GenRandom* /*request*/, ::SMSG_GenRandom* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGenRandom(::grpc::ServerContext* context, ::CMSG_GenRandom* request, ::grpc::ServerAsyncResponseWriter< ::SMSG_GenRandom>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AESEncrypt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AESEncrypt() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_AESEncrypt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AESEncrypt(::grpc::ServerContext* /*context*/, const ::CMSG_AESOperation* /*request*/, ::SMSG_AESResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAESEncrypt(::grpc::ServerContext* context, ::CMSG_AESOperation* request, ::grpc::ServerAsyncResponseWriter< ::SMSG_AESResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AESDecrypt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AESDecrypt() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_AESDecrypt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AESDecrypt(::grpc::ServerContext* /*context*/, const ::CMSG_AESOperation* /*request*/, ::SMSG_AESResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAESDecrypt(::grpc::ServerContext* context, ::CMSG_AESOperation* request, ::grpc::ServerAsyncResponseWriter< ::SMSG_AESResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DESFireISOAuth1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DESFireISOAuth1() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_DESFireISOAuth1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireISOAuth1(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireISOAuth_Step1* /*request*/, ::SMSG_DesfireISOAuth_Step1* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDESFireISOAuth1(::grpc::ServerContext* context, ::CMSG_DesfireISOAuth_Step1* request, ::grpc::ServerAsyncResponseWriter< ::SMSG_DesfireISOAuth_Step1>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DESFireISOAuth2 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DESFireISOAuth2() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_DESFireISOAuth2() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireISOAuth2(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireAuth_Step2* /*request*/, ::SMSG_DesfireAuth_Step2* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDESFireISOAuth2(::grpc::ServerContext* context, ::CMSG_DesfireAuth_Step2* request, ::grpc::ServerAsyncResponseWriter< ::SMSG_DesfireAuth_Step2>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DESFireAESAuth1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DESFireAESAuth1() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_DESFireAESAuth1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireAESAuth1(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireAESAuth_Step1* /*request*/, ::SMSG_DesfireAESAuth_Step1* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDESFireAESAuth1(::grpc::ServerContext* context, ::CMSG_DesfireAESAuth_Step1* request, ::grpc::ServerAsyncResponseWriter< ::SMSG_DesfireAESAuth_Step1>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DESFireAESAuth2 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DESFireAESAuth2() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_DESFireAESAuth2() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireAESAuth2(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireAuth_Step2* /*request*/, ::SMSG_DesfireAuth_Step2* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDESFireAESAuth2(::grpc::ServerContext* context, ::CMSG_DesfireAuth_Step2* request, ::grpc::ServerAsyncResponseWriter< ::SMSG_DesfireAuth_Step2>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DESFireChangeKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DESFireChangeKey() {
      ::grpc::Service::MarkMethodAsync(7);
    }
    ~WithAsyncMethod_DESFireChangeKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireChangeKey(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireChangeKey* /*request*/, ::SMSG_DesfireChangeKey* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDESFireChangeKey(::grpc::ServerContext* context, ::CMSG_DesfireChangeKey* request, ::grpc::ServerAsyncResponseWriter< ::SMSG_DesfireChangeKey>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GenRandom<WithAsyncMethod_AESEncrypt<WithAsyncMethod_AESDecrypt<WithAsyncMethod_DESFireISOAuth1<WithAsyncMethod_DESFireISOAuth2<WithAsyncMethod_DESFireAESAuth1<WithAsyncMethod_DESFireAESAuth2<WithAsyncMethod_DESFireChangeKey<Service > > > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GenRandom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GenRandom() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::CMSG_GenRandom, ::SMSG_GenRandom>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::CMSG_GenRandom* request, ::SMSG_GenRandom* response) { return this->GenRandom(context, request, response); }));}
    void SetMessageAllocatorFor_GenRandom(
        ::grpc::MessageAllocator< ::CMSG_GenRandom, ::SMSG_GenRandom>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::CMSG_GenRandom, ::SMSG_GenRandom>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GenRandom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenRandom(::grpc::ServerContext* /*context*/, const ::CMSG_GenRandom* /*request*/, ::SMSG_GenRandom* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GenRandom(
      ::grpc::CallbackServerContext* /*context*/, const ::CMSG_GenRandom* /*request*/, ::SMSG_GenRandom* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AESEncrypt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AESEncrypt() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::CMSG_AESOperation, ::SMSG_AESResult>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::CMSG_AESOperation* request, ::SMSG_AESResult* response) { return this->AESEncrypt(context, request, response); }));}
    void SetMessageAllocatorFor_AESEncrypt(
        ::grpc::MessageAllocator< ::CMSG_AESOperation, ::SMSG_AESResult>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::CMSG_AESOperation, ::SMSG_AESResult>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AESEncrypt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AESEncrypt(::grpc::ServerContext* /*context*/, const ::CMSG_AESOperation* /*request*/, ::SMSG_AESResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AESEncrypt(
      ::grpc::CallbackServerContext* /*context*/, const ::CMSG_AESOperation* /*request*/, ::SMSG_AESResult* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AESDecrypt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AESDecrypt() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::CMSG_AESOperation, ::SMSG_AESResult>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::CMSG_AESOperation* request, ::SMSG_AESResult* response) { return this->AESDecrypt(context, request, response); }));}
    void SetMessageAllocatorFor_AESDecrypt(
        ::grpc::MessageAllocator< ::CMSG_AESOperation, ::SMSG_AESResult>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::CMSG_AESOperation, ::SMSG_AESResult>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AESDecrypt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AESDecrypt(::grpc::ServerContext* /*context*/, const ::CMSG_AESOperation* /*request*/, ::SMSG_AESResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AESDecrypt(
      ::grpc::CallbackServerContext* /*context*/, const ::CMSG_AESOperation* /*request*/, ::SMSG_AESResult* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DESFireISOAuth1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DESFireISOAuth1() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::CMSG_DesfireISOAuth_Step1, ::SMSG_DesfireISOAuth_Step1>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::CMSG_DesfireISOAuth_Step1* request, ::SMSG_DesfireISOAuth_Step1* response) { return this->DESFireISOAuth1(context, request, response); }));}
    void SetMessageAllocatorFor_DESFireISOAuth1(
        ::grpc::MessageAllocator< ::CMSG_DesfireISOAuth_Step1, ::SMSG_DesfireISOAuth_Step1>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::CMSG_DesfireISOAuth_Step1, ::SMSG_DesfireISOAuth_Step1>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DESFireISOAuth1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireISOAuth1(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireISOAuth_Step1* /*request*/, ::SMSG_DesfireISOAuth_Step1* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DESFireISOAuth1(
      ::grpc::CallbackServerContext* /*context*/, const ::CMSG_DesfireISOAuth_Step1* /*request*/, ::SMSG_DesfireISOAuth_Step1* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DESFireISOAuth2 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DESFireISOAuth2() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::CMSG_DesfireAuth_Step2, ::SMSG_DesfireAuth_Step2>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::CMSG_DesfireAuth_Step2* request, ::SMSG_DesfireAuth_Step2* response) { return this->DESFireISOAuth2(context, request, response); }));}
    void SetMessageAllocatorFor_DESFireISOAuth2(
        ::grpc::MessageAllocator< ::CMSG_DesfireAuth_Step2, ::SMSG_DesfireAuth_Step2>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::CMSG_DesfireAuth_Step2, ::SMSG_DesfireAuth_Step2>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DESFireISOAuth2() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireISOAuth2(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireAuth_Step2* /*request*/, ::SMSG_DesfireAuth_Step2* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DESFireISOAuth2(
      ::grpc::CallbackServerContext* /*context*/, const ::CMSG_DesfireAuth_Step2* /*request*/, ::SMSG_DesfireAuth_Step2* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DESFireAESAuth1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DESFireAESAuth1() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::CMSG_DesfireAESAuth_Step1, ::SMSG_DesfireAESAuth_Step1>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::CMSG_DesfireAESAuth_Step1* request, ::SMSG_DesfireAESAuth_Step1* response) { return this->DESFireAESAuth1(context, request, response); }));}
    void SetMessageAllocatorFor_DESFireAESAuth1(
        ::grpc::MessageAllocator< ::CMSG_DesfireAESAuth_Step1, ::SMSG_DesfireAESAuth_Step1>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::CMSG_DesfireAESAuth_Step1, ::SMSG_DesfireAESAuth_Step1>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DESFireAESAuth1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireAESAuth1(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireAESAuth_Step1* /*request*/, ::SMSG_DesfireAESAuth_Step1* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DESFireAESAuth1(
      ::grpc::CallbackServerContext* /*context*/, const ::CMSG_DesfireAESAuth_Step1* /*request*/, ::SMSG_DesfireAESAuth_Step1* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DESFireAESAuth2 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DESFireAESAuth2() {
      ::grpc::Service::MarkMethodCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::CMSG_DesfireAuth_Step2, ::SMSG_DesfireAuth_Step2>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::CMSG_DesfireAuth_Step2* request, ::SMSG_DesfireAuth_Step2* response) { return this->DESFireAESAuth2(context, request, response); }));}
    void SetMessageAllocatorFor_DESFireAESAuth2(
        ::grpc::MessageAllocator< ::CMSG_DesfireAuth_Step2, ::SMSG_DesfireAuth_Step2>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(6);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::CMSG_DesfireAuth_Step2, ::SMSG_DesfireAuth_Step2>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DESFireAESAuth2() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireAESAuth2(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireAuth_Step2* /*request*/, ::SMSG_DesfireAuth_Step2* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DESFireAESAuth2(
      ::grpc::CallbackServerContext* /*context*/, const ::CMSG_DesfireAuth_Step2* /*request*/, ::SMSG_DesfireAuth_Step2* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DESFireChangeKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DESFireChangeKey() {
      ::grpc::Service::MarkMethodCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::CMSG_DesfireChangeKey, ::SMSG_DesfireChangeKey>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::CMSG_DesfireChangeKey* request, ::SMSG_DesfireChangeKey* response) { return this->DESFireChangeKey(context, request, response); }));}
    void SetMessageAllocatorFor_DESFireChangeKey(
        ::grpc::MessageAllocator< ::CMSG_DesfireChangeKey, ::SMSG_DesfireChangeKey>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(7);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::CMSG_DesfireChangeKey, ::SMSG_DesfireChangeKey>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DESFireChangeKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireChangeKey(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireChangeKey* /*request*/, ::SMSG_DesfireChangeKey* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DESFireChangeKey(
      ::grpc::CallbackServerContext* /*context*/, const ::CMSG_DesfireChangeKey* /*request*/, ::SMSG_DesfireChangeKey* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GenRandom<WithCallbackMethod_AESEncrypt<WithCallbackMethod_AESDecrypt<WithCallbackMethod_DESFireISOAuth1<WithCallbackMethod_DESFireISOAuth2<WithCallbackMethod_DESFireAESAuth1<WithCallbackMethod_DESFireAESAuth2<WithCallbackMethod_DESFireChangeKey<Service > > > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GenRandom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GenRandom() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GenRandom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenRandom(::grpc::ServerContext* /*context*/, const ::CMSG_GenRandom* /*request*/, ::SMSG_GenRandom* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AESEncrypt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AESEncrypt() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_AESEncrypt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AESEncrypt(::grpc::ServerContext* /*context*/, const ::CMSG_AESOperation* /*request*/, ::SMSG_AESResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AESDecrypt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AESDecrypt() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_AESDecrypt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AESDecrypt(::grpc::ServerContext* /*context*/, const ::CMSG_AESOperation* /*request*/, ::SMSG_AESResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DESFireISOAuth1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DESFireISOAuth1() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_DESFireISOAuth1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireISOAuth1(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireISOAuth_Step1* /*request*/, ::SMSG_DesfireISOAuth_Step1* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DESFireISOAuth2 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DESFireISOAuth2() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_DESFireISOAuth2() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireISOAuth2(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireAuth_Step2* /*request*/, ::SMSG_DesfireAuth_Step2* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DESFireAESAuth1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DESFireAESAuth1() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_DESFireAESAuth1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireAESAuth1(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireAESAuth_Step1* /*request*/, ::SMSG_DesfireAESAuth_Step1* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DESFireAESAuth2 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DESFireAESAuth2() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_DESFireAESAuth2() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireAESAuth2(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireAuth_Step2* /*request*/, ::SMSG_DesfireAuth_Step2* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DESFireChangeKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DESFireChangeKey() {
      ::grpc::Service::MarkMethodGeneric(7);
    }
    ~WithGenericMethod_DESFireChangeKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireChangeKey(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireChangeKey* /*request*/, ::SMSG_DesfireChangeKey* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GenRandom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GenRandom() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GenRandom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenRandom(::grpc::ServerContext* /*context*/, const ::CMSG_GenRandom* /*request*/, ::SMSG_GenRandom* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGenRandom(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AESEncrypt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AESEncrypt() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_AESEncrypt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AESEncrypt(::grpc::ServerContext* /*context*/, const ::CMSG_AESOperation* /*request*/, ::SMSG_AESResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAESEncrypt(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AESDecrypt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AESDecrypt() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_AESDecrypt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AESDecrypt(::grpc::ServerContext* /*context*/, const ::CMSG_AESOperation* /*request*/, ::SMSG_AESResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAESDecrypt(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DESFireISOAuth1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DESFireISOAuth1() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_DESFireISOAuth1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireISOAuth1(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireISOAuth_Step1* /*request*/, ::SMSG_DesfireISOAuth_Step1* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDESFireISOAuth1(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DESFireISOAuth2 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DESFireISOAuth2() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_DESFireISOAuth2() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireISOAuth2(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireAuth_Step2* /*request*/, ::SMSG_DesfireAuth_Step2* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDESFireISOAuth2(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DESFireAESAuth1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DESFireAESAuth1() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_DESFireAESAuth1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireAESAuth1(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireAESAuth_Step1* /*request*/, ::SMSG_DesfireAESAuth_Step1* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDESFireAESAuth1(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DESFireAESAuth2 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DESFireAESAuth2() {
      ::grpc::Service::MarkMethodRaw(6);
    }
    ~WithRawMethod_DESFireAESAuth2() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireAESAuth2(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireAuth_Step2* /*request*/, ::SMSG_DesfireAuth_Step2* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDESFireAESAuth2(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DESFireChangeKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DESFireChangeKey() {
      ::grpc::Service::MarkMethodRaw(7);
    }
    ~WithRawMethod_DESFireChangeKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireChangeKey(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireChangeKey* /*request*/, ::SMSG_DesfireChangeKey* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDESFireChangeKey(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GenRandom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GenRandom() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GenRandom(context, request, response); }));
    }
    ~WithRawCallbackMethod_GenRandom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenRandom(::grpc::ServerContext* /*context*/, const ::CMSG_GenRandom* /*request*/, ::SMSG_GenRandom* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GenRandom(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AESEncrypt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AESEncrypt() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AESEncrypt(context, request, response); }));
    }
    ~WithRawCallbackMethod_AESEncrypt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AESEncrypt(::grpc::ServerContext* /*context*/, const ::CMSG_AESOperation* /*request*/, ::SMSG_AESResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AESEncrypt(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AESDecrypt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AESDecrypt() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AESDecrypt(context, request, response); }));
    }
    ~WithRawCallbackMethod_AESDecrypt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AESDecrypt(::grpc::ServerContext* /*context*/, const ::CMSG_AESOperation* /*request*/, ::SMSG_AESResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AESDecrypt(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DESFireISOAuth1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DESFireISOAuth1() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DESFireISOAuth1(context, request, response); }));
    }
    ~WithRawCallbackMethod_DESFireISOAuth1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireISOAuth1(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireISOAuth_Step1* /*request*/, ::SMSG_DesfireISOAuth_Step1* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DESFireISOAuth1(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DESFireISOAuth2 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DESFireISOAuth2() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DESFireISOAuth2(context, request, response); }));
    }
    ~WithRawCallbackMethod_DESFireISOAuth2() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireISOAuth2(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireAuth_Step2* /*request*/, ::SMSG_DesfireAuth_Step2* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DESFireISOAuth2(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DESFireAESAuth1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DESFireAESAuth1() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DESFireAESAuth1(context, request, response); }));
    }
    ~WithRawCallbackMethod_DESFireAESAuth1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireAESAuth1(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireAESAuth_Step1* /*request*/, ::SMSG_DesfireAESAuth_Step1* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DESFireAESAuth1(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DESFireAESAuth2 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DESFireAESAuth2() {
      ::grpc::Service::MarkMethodRawCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DESFireAESAuth2(context, request, response); }));
    }
    ~WithRawCallbackMethod_DESFireAESAuth2() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireAESAuth2(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireAuth_Step2* /*request*/, ::SMSG_DesfireAuth_Step2* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DESFireAESAuth2(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DESFireChangeKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DESFireChangeKey() {
      ::grpc::Service::MarkMethodRawCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DESFireChangeKey(context, request, response); }));
    }
    ~WithRawCallbackMethod_DESFireChangeKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DESFireChangeKey(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireChangeKey* /*request*/, ::SMSG_DesfireChangeKey* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DESFireChangeKey(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GenRandom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GenRandom() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::CMSG_GenRandom, ::SMSG_GenRandom>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::CMSG_GenRandom, ::SMSG_GenRandom>* streamer) {
                       return this->StreamedGenRandom(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GenRandom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GenRandom(::grpc::ServerContext* /*context*/, const ::CMSG_GenRandom* /*request*/, ::SMSG_GenRandom* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGenRandom(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::CMSG_GenRandom,::SMSG_GenRandom>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AESEncrypt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AESEncrypt() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::CMSG_AESOperation, ::SMSG_AESResult>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::CMSG_AESOperation, ::SMSG_AESResult>* streamer) {
                       return this->StreamedAESEncrypt(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AESEncrypt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AESEncrypt(::grpc::ServerContext* /*context*/, const ::CMSG_AESOperation* /*request*/, ::SMSG_AESResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAESEncrypt(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::CMSG_AESOperation,::SMSG_AESResult>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AESDecrypt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AESDecrypt() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::CMSG_AESOperation, ::SMSG_AESResult>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::CMSG_AESOperation, ::SMSG_AESResult>* streamer) {
                       return this->StreamedAESDecrypt(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AESDecrypt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AESDecrypt(::grpc::ServerContext* /*context*/, const ::CMSG_AESOperation* /*request*/, ::SMSG_AESResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAESDecrypt(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::CMSG_AESOperation,::SMSG_AESResult>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DESFireISOAuth1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DESFireISOAuth1() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::CMSG_DesfireISOAuth_Step1, ::SMSG_DesfireISOAuth_Step1>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::CMSG_DesfireISOAuth_Step1, ::SMSG_DesfireISOAuth_Step1>* streamer) {
                       return this->StreamedDESFireISOAuth1(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DESFireISOAuth1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DESFireISOAuth1(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireISOAuth_Step1* /*request*/, ::SMSG_DesfireISOAuth_Step1* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDESFireISOAuth1(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::CMSG_DesfireISOAuth_Step1,::SMSG_DesfireISOAuth_Step1>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DESFireISOAuth2 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DESFireISOAuth2() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::CMSG_DesfireAuth_Step2, ::SMSG_DesfireAuth_Step2>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::CMSG_DesfireAuth_Step2, ::SMSG_DesfireAuth_Step2>* streamer) {
                       return this->StreamedDESFireISOAuth2(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DESFireISOAuth2() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DESFireISOAuth2(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireAuth_Step2* /*request*/, ::SMSG_DesfireAuth_Step2* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDESFireISOAuth2(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::CMSG_DesfireAuth_Step2,::SMSG_DesfireAuth_Step2>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DESFireAESAuth1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DESFireAESAuth1() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::CMSG_DesfireAESAuth_Step1, ::SMSG_DesfireAESAuth_Step1>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::CMSG_DesfireAESAuth_Step1, ::SMSG_DesfireAESAuth_Step1>* streamer) {
                       return this->StreamedDESFireAESAuth1(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DESFireAESAuth1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DESFireAESAuth1(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireAESAuth_Step1* /*request*/, ::SMSG_DesfireAESAuth_Step1* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDESFireAESAuth1(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::CMSG_DesfireAESAuth_Step1,::SMSG_DesfireAESAuth_Step1>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DESFireAESAuth2 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DESFireAESAuth2() {
      ::grpc::Service::MarkMethodStreamed(6,
        new ::grpc::internal::StreamedUnaryHandler<
          ::CMSG_DesfireAuth_Step2, ::SMSG_DesfireAuth_Step2>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::CMSG_DesfireAuth_Step2, ::SMSG_DesfireAuth_Step2>* streamer) {
                       return this->StreamedDESFireAESAuth2(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DESFireAESAuth2() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DESFireAESAuth2(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireAuth_Step2* /*request*/, ::SMSG_DesfireAuth_Step2* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDESFireAESAuth2(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::CMSG_DesfireAuth_Step2,::SMSG_DesfireAuth_Step2>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DESFireChangeKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DESFireChangeKey() {
      ::grpc::Service::MarkMethodStreamed(7,
        new ::grpc::internal::StreamedUnaryHandler<
          ::CMSG_DesfireChangeKey, ::SMSG_DesfireChangeKey>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::CMSG_DesfireChangeKey, ::SMSG_DesfireChangeKey>* streamer) {
                       return this->StreamedDESFireChangeKey(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DESFireChangeKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DESFireChangeKey(::grpc::ServerContext* /*context*/, const ::CMSG_DesfireChangeKey* /*request*/, ::SMSG_DesfireChangeKey* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDESFireChangeKey(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::CMSG_DesfireChangeKey,::SMSG_DesfireChangeKey>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GenRandom<WithStreamedUnaryMethod_AESEncrypt<WithStreamedUnaryMethod_AESDecrypt<WithStreamedUnaryMethod_DESFireISOAuth1<WithStreamedUnaryMethod_DESFireISOAuth2<WithStreamedUnaryMethod_DESFireAESAuth1<WithStreamedUnaryMethod_DESFireAESAuth2<WithStreamedUnaryMethod_DESFireChangeKey<Service > > > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GenRandom<WithStreamedUnaryMethod_AESEncrypt<WithStreamedUnaryMethod_AESDecrypt<WithStreamedUnaryMethod_DESFireISOAuth1<WithStreamedUnaryMethod_DESFireISOAuth2<WithStreamedUnaryMethod_DESFireAESAuth1<WithStreamedUnaryMethod_DESFireAESAuth2<WithStreamedUnaryMethod_DESFireChangeKey<Service > > > > > > > > StreamedService;
};


#endif  // GRPC_iks_2eproto__INCLUDED
